// --- BASE DE DATOS DE EJERCICIOS ---
// t: 'c' (Compuesto) | t: 'i' (Aislado)
// v: 'Link de YouTube' (Opcional)

export const EXERCISES = [
    // --- CUÁDRICEPS ---
    // EJEMPLO CON VÍDEO (He puesto uno genérico, cámbialo por el tuyo)
    {n:"Sentadilla con Barra", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c", v:"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
    
    // El resto siguen igual (sin vídeo por defecto)
    {n:"Sentadilla Frontal Barra", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Jaca (Hack)", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Jaca Inversa", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Cinturón", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Multipower", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Goblet", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Sissy", img:"img/cuadriceps.png", m:"Cuádriceps", t:"i"},
    {n:"Sentadilla Sissy Banco", img:"img/cuadriceps.png", m:"Cuádriceps", t:"i"},
    {n:"Sentadilla Sumo Mancuerna", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Búlgara Mancuernas", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Búlgara Multipower", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Pistol", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Zumo", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Jefferson", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Hack Sentado", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Sentadilla Pendulum", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Prensa de Piernas 45º", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Prensa Horizontal", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Prensa Vertical", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Prensa Unilateral", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Extensión Cuádriceps", img:"img/cuadriceps.png", m:"Cuádriceps", t:"i"},
    {n:"Extensión Cuádriceps Unilateral", img:"img/cuadriceps.png", m:"Cuádriceps", t:"i"},
    {n:"Zancadas Barra", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Zancadas Mancuernas", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Zancadas Caminando", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Zancadas Atrás Multipower", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Zancadas Estáticas", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Step-Up Cajón", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Step-Up con Barra", img:"img/cuadriceps.png", m:"Cuádriceps", t:"c"},
    {n:"Aductores en Máquina", img:"img/cuadriceps.png", m:"Cuádriceps", t:"i"},

    // --- ISQUIOTIBIALES ---
    {n:"Curl Femoral Tumbado", img:"img/isquiotibiales.png", m:"Isquios", t:"i"},
    {n:"Curl Femoral Sentado", img:"img/isquiotibiales.png", m:"Isquios", t:"i"},
    {n:"Curl Femoral de Pie", img:"img/isquiotibiales.png", m:"Isquios", t:"i"},
    {n:"Curl Femoral Unilateral", img:"img/isquiotibiales.png", m:"Isquios", t:"i"},
    {n:"Curl Nórdico", img:"img/isquiotibiales.png", m:"Isquios", t:"i"},
    {n:"Curl Nórdico Polea", img:"img/isquiotibiales.png", m:"Isquios", t:"i"},
    {n:"Curl Swiss Ball", img:"img/isquiotibiales.png", m:"Isquios", t:"i"},
    {n:"Peso Muerto Rumano Barra", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Peso Muerto Rumano Mancuernas", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Peso Muerto Rumano Multipower", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Peso Muerto Rumano Unilateral", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Peso Muerto Piernas Rígidas", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Buenos Días Barra", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Buenos Días Multipower", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Buenos Días Banda Elástica", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},
    {n:"Glute Ham Raise (GHR)", img:"img/isquiotibiales.png", m:"Isquios", t:"c"},

    // --- GLÚTEOS ---
    {n:"Hip Thrust Barra", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Hip Thrust Máquina", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Hip Thrust Multipower", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Hip Thrust Unilateral", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Hip Thrust Mancuerna", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Puente de Glúteo Suelo", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Kas Glute Bridge", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Sentadilla Búlgara (Enfoque Glúteo)", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Patada Glúteo Polea", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Patada Glúteo Máquina", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Patada Glúteo Suelo", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Abducción Máquina", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Abducción Polea", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Abducción con Gomas", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Prensa Glúteos (Pies altos)", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Frog Pumps", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Step-Up Lateral", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Pull Through Polea", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Hiperextensiones Glúteo (45º)", img:"img/gluteos.png", m:"Glúteos", t:"i"},
    {n:"Peso Muerto Sumo", img:"img/gluteos.png", m:"Glúteos", t:"c"},
    {n:"Monster Walk", img:"img/gluteos.png", m:"Glúteos", t:"i"},

    // --- GEMELOS ---
    {n:"Gemelo Sentado Máquina", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Gemelo Sentado Barra", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Gemelo de Pie Máquina", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Gemelo de Pie Multipower", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Gemelo de Pie Mancuernas", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Gemelo en Prensa", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Gemelo Donkey (Burro)", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Gemelo Unilateral", img:"img/gemelos.png", m:"Gemelos", t:"i"},
    {n:"Sóleo en Máquina", img:"img/gemelos.png", m:"Gemelos", t:"i"},

    // --- ESPALDA ---
    {n:"Peso Muerto Convencional", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Peso Muerto Déficit", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Rack Pull", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Dominadas Pronas", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Dominadas Supinas", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Dominadas Neutras", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Dominadas Asistidas", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Jalón al Pecho", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Jalón al Pecho Supino", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Jalón Cerrado (Triángulo)", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Jalón Neutro", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Jalón Unilateral Polea", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Jalón Trasnuca", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Jalón Brazos Rectos (Pullover Polea)", img:"img/espalda.png", m:"Espalda", t:"i"},
    {n:"Remo con Barra 90º", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo con Barra 45º (Yates)", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Pendlay", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Mancuerna Unilateral", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Mancuerna Dos Brazos", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Mancuernas Apoyo Pecho", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo T (Barra esquina)", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo T con Apoyo Pecho", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Gironda (Polea Baja)", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo en Punta", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Kroc", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Meadows", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Máquina Placas", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Máquina Discos (Hammer)", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo Invertido (TRX/Barra)", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Remo al Mentón (Cuello)", img:"img/espalda.png", m:"Espalda", t:"c"},
    {n:"Hiperextensiones Lumbares", img:"img/espalda.png", m:"Espalda", t:"i"},
    {n:"Superman Suelo", img:"img/espalda.png", m:"Espalda", t:"i"},
    {n:"Face Pull", img:"img/hombros.png", m:"Hombros", t:"i"},

    // --- PECHO ---
    {n:"Press Banca Barra", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Banca Mancuernas", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Banca Multipower", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Inclinado Barra", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Inclinado Mancuernas", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Inclinado Multipower", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Declinado Barra", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Declinado Mancuernas", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Declinado Multipower", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Pecho Máquina Sentado", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Hammer Strength", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Iso-Lateral", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Guillotina", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Svend", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Press Landmine", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Press Suelo (Floor Press)", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Aperturas Mancuernas Planas", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Aperturas Mancuernas Inclinadas", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Aperturas en Máquina (Peck Deck)", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Contractora de Pecho", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Cruce de Poleas Alta", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Cruce de Poleas Media", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Cruce de Poleas Baja", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Fondos en Paralelas", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Fondos Asistidos", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Pullover Mancuerna", img:"img/pecho.png", m:"Pecho", t:"i"},
    {n:"Flexiones (Push Ups)", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Flexiones Inclinadas", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Flexiones Declinadas", img:"img/pecho.png", m:"Pecho", t:"c"},
    {n:"Flexiones Diamante", img:"img/pecho.png", m:"Pecho", t:"c"},

    // --- HOMBROS ---
    {n:"Press Militar Barra de Pie", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Press Militar Barra Sentado", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Press Hombro Mancuernas", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Press Hombro Multipower", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Press Hombro Máquina", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Press Arnold", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Press Trasnuca", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Press Landmine Unilateral", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Elevaciones Laterales Mancuerna", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Laterales Polea", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Laterales Máquina", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Laterales Sentado", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Laterales Egipcias", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Frontales Mancuerna", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Frontales Barra", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Frontales Disco", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Elevaciones Frontales Polea", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Pájaros Mancuerna (Posterior)", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Pájaros en Máquina", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Face Pull Polea Alta", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Cruces Polea Inversos", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Remo al Mentón Barra", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Remo al Mentón Polea", img:"img/hombros.png", m:"Hombros", t:"c"},
    {n:"Encogimientos Barra (Trapecio)", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Encogimientos Mancuerna", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Encogimientos Multipower", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Encogimientos en Máquina", img:"img/hombros.png", m:"Hombros", t:"i"},
    {n:"Y-Raise Mancuernas", img:"img/hombros.png", m:"Hombros", t:"i"},

    // --- BÍCEPS ---
    {n:"Curl con Barra Recta (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl con Barra Z (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl con Mancuernas Supino (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl con Mancuernas Alterno (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Martillo Mancuernas (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Martillo Cuerda Polea (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Predicador Barra Z (Scott)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Predicador Mancuerna", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Predicador Máquina", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Concentrado (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Araña (Spider Curl)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl en Banco Inclinado (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Polea Baja (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Polea Alta (Doble)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Bayesiano (Espalda a Polea)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl 21 (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Zottman (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl con Disco (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Dominadas Supinas (Bíceps)", img:"img/biceps.png", m:"Bíceps", t:"c"},
    {n:"Curl de Muñeca (Antebrazo)", img:"img/biceps.png", m:"Bíceps", t:"i"},
    {n:"Curl Inverso Barra (Antebrazo)", img:"img/biceps.png", m:"Bíceps", t:"i"},

    // --- TRÍCEPS ---
    {n:"Extensión Polea Cuerda", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Extensión Polea Barra Recta", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Extensión Polea Barra V", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Extensión Polea Unilateral", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Extensión Katana", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Press Francés Barra Z", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Press Francés Mancuernas", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Press Francés Polea", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Rompecráneos", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Press Cerrado Barra", img:"img/triceps.png", m:"Tríceps", t:"c"},
    {n:"Press Cerrado Multipower", img:"img/triceps.png", m:"Tríceps", t:"c"},
    {n:"Fondos Tríceps (Dips)", img:"img/triceps.png", m:"Tríceps", t:"c"},
    {n:"Fondos entre Bancos", img:"img/triceps.png", m:"Tríceps", t:"c"},
    {n:"Fondos en Máquina", img:"img/triceps.png", m:"Tríceps", t:"c"},
    {n:"Patada de Tríceps Mancuerna", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Patada de Tríceps Polea", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Copa Tríceps a Dos Manos", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Copa Tríceps Unilateral", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"Extensiones Trasnuca Polea", img:"img/triceps.png", m:"Tríceps", t:"i"},
    {n:"JM Press", img:"img/triceps.png", m:"Tríceps", t:"c"},
    {n:"Tate Press", img:"img/triceps.png", m:"Tríceps", t:"i"},

    // --- ABDOMINALES ---
    {n:"Crunch Suelo", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Crunch Polea Alta", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Crunch Máquina", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Crunch en Fitball", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Elevación de Piernas Colgado", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Elevación de Piernas Suelo", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Elevación de Rodillas (Silla romana)", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Rueda Abdominal (Ab Wheel)", img:"img/abs.png", m:"Abs", t:"c"},
    {n:"Plancha Abdominal (Plank)", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Plancha Lateral", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"V-Ups", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Tijeras", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Bicicleta", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Mountain Climbers", img:"img/abs.png", m:"Abs", t:"c"},
    {n:"Russian Twist (Giros)", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Woodchopper Polea (Leñador)", img:"img/abs.png", m:"Abs", t:"c"},
    {n:"Press Pallof", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Toques de Talón", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Hipopresivos", img:"img/abs.png", m:"Abs", t:"i"},
    {n:"Dragon Flag", img:"img/abs.png", m:"Abs", t:"c"}
];
